#!/bin/bash

echo "moving to release"
if [ ! -d "release" ]; then
	mkdir release
fi

cd release

echo "cmake plugin"

cmake ..

echo "make plugin"

make all

echo "Plugin done, locate in libs folder"
